---
  - hosts: all
    become: yes
  
    tasks:  
    - name: install yum utiils
      yum:
        name: yum-utils
        state: present 
    
    - name: install the repo
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      
    - name: install terraform
      yum:
        name: terraform
        state: present
        update_cache: true
  
    - name: install git headers
      yum:
        name: git
        state: present
    