---
- hosts: all
  become: yes

  tasks:
  - name: get repo
    get_url:
        url: https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/cloudera-manager.repo
        dest: /etc/yum.repos.d/

  - name: add cldr rpm key
    rpm_key:
        state: present
        key: https://archive.cloudera.com/cm6/6.3.1/redhat7/yum/RPM-GPG-KEY-cloudera

  - name: remove openjdk
    yum:
        name: '*openjdk*'
        state: removed

  - name: install oracle jdk
    yum:
        name: oracle-j2sdk1.8
        state: installed
        update_cache: yes

